sudo: required
services:
  - docker

before_install:
  - docker build -t lxgttzz2/my-repo:react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lxgttzz2/my-repo:react-test npm test

after_success:
  - docker build -t lxgttzz2/my-repo:multi-client ./client
  - docker build -t lxgttzz2/my-repo:multi-nginx ./nginx
  - docker build -t lxgttzz2/my-repo:multi-server ./server
  - docker build -t lxgttzz2/my-repo:multi-worker ./worker
  # log us into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push lxgttzz2/my-repo:multi-client
  - docker push lxgttzz2/my-repo:multi-nginx
  - docker push lxgttzz2/my-repo:multi-server
  - docker push lxgttzz2/my-repo:multi-worker
