sudo: required
services:
  - docker

before_install:
  - docker build -t diegofasan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true diegofasan/react-test npm test

after_success:
  - docker build -t diegofasan/multi-client ./client
  - docker build -t diegofasan/multi-nginx ./nginx
  - docker build -t diegofasan/multi-server ./server
  - docker build -t diegofasan/multi-worker ./worker
  # log us into docker CLI
  - echo "$DOCKER_ID"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push diegofasan/multi-client
  - docker push diegofasan/multi-nginx
  - docker push diegofasan/multi-server
  - docker push diegofasan/multi-worker
